export const MATCH_QUESTION_COUNT = 10;
export const QUESTION_DURATION_MS = 15_000;
export const INSTRUCTIONS_DURATION_MS = 5_000;
export const COUNTDOWN_DURATION_MS = 3_000;
export const ANSWER_LOCK_DURATION_MS = 2_000;
export const BATTLE_RESULT_DURATION_MS = 10_000;
export const LEADERBOARD_DURATION_MS = 10_000;
export const FINISHED_DURATION_MS = 3_000;
