import type { Question } from "@/lib/types/game";

export const ROUND_CATEGORY_PLAN = [
  { order: 1, category: "Justas LAI en general", count: 2 },
  { order: 2, category: "Historia de las Justas en Mayagüez", count: 2 },
  { order: 3, category: "Justas LAI Baloncesto 2024-2025", count: 2 },
  { order: 4, category: "Justas LAI Baile 2024-2025", count: 2 },
  { order: 5, category: "Justas LAI Porrismo 2024-2025", count: 2 },
] as const;

function buildQuestion(
  categoryOrder: number,
  index: number,
  category: string,
  prompt: string,
  choices: Question["choices"],
  correctChoice: Question["correctChoice"],
): Question {
  const questionId = `c${categoryOrder}-q${index}`;
  return {
    questionId,
    sourceRowId: questionId,
    prompt,
    choices,
    correctChoice,
    categoryOrder,
    category,
    difficulty: "medium",
    isActive: true,
  };
}

export const SAMPLE_QUESTIONS: Question[] = [
  buildQuestion(1, 1, "Justas LAI en general", "¿Cuál es el principal evento universitario deportivo en Puerto Rico que combina competencias de pista y campo, conciertos y actividades culturales?", { A: "Juegos Panamericanos", B: "Festival Deportivo Intercolegial", C: "Justas de la LAI", D: "Olimpiadas Escolares" }, "C"),
  buildQuestion(1, 2, "Justas LAI en general", "¿En qué año fue fundada oficialmente la Liga Atlética Interuniversitaria (LAI) de Puerto Rico?", { A: "1929", B: "1950", C: "1972", D: "1985" }, "A"),
  buildQuestion(1, 3, "Justas LAI en general", "¿Cuántas universidades forman parte actualmente de la LAI?", { A: "8", B: "12", C: "17", D: "21" }, "C"),
  buildQuestion(1, 4, "Justas LAI en general", "¿Qué disciplina se incorporó como la primera prueba mixta en atletismo de las Justas en 2023?", { A: "Relevo 4×100 mixto", B: "Relevo 4×400 mixto", C: "Salto triple mixto", D: "Lanzamiento de jabalina mixto" }, "B"),
  buildQuestion(1, 5, "Justas LAI en general", "¿Qué ciudad ha sido tradicionalmente la sede de las Justas desde los años 90?", { A: "San Juan", B: "Bayamón", C: "Ponce", D: "Mayagüez" }, "C"),
  buildQuestion(1, 6, "Justas LAI en general", "¿Cuántos deportes oficiales ofrece actualmente la LAI para hombres y mujeres sin contar deportes mixtos?", { A: "10", B: "15", C: "18", D: "22" }, "C"),
  buildQuestion(1, 7, "Justas LAI en general", "¿Cuál es el impacto estimado de asistencia a los eventos culturales de las Justas?", { A: "10,000 personas", B: "25,000 personas", C: "100,000 personas", D: "150,000 personas" }, "D"),
  buildQuestion(1, 8, "Justas LAI en general", "¿Qué trofeo se otorga a la universidad con el mejor desempeño general durante el año deportivo?", { A: "Copa Olímpica", B: "Copa Luis F. Sambolín", C: "Copa Campeón Global", D: "Copa Interuniversitaria" }, "B"),
  buildQuestion(1, 9, "Justas LAI en general", "¿Qué institución ganó la Copa Luis F. Sambolín en el año 2023?", { A: "UPR Mayagüez", B: "Universidad Interamericana", C: "Universidad Ana G. Méndez (UAGM)", D: "UPR Río Piedras" }, "C"),
  buildQuestion(1, 10, "Justas LAI en general", "¿Qué impacto económico tienen las Justas para la ciudad sede?", { A: "Bajo, debido a la falta de turistas", B: "Neutro, solo afecta la economía universitaria", C: "Alto, generando ocupación hotelera máxima y ventas locales masivas", D: "Insignificante, porque es solo un evento de estudiantes" }, "C"),
  buildQuestion(1, 11, "Justas LAI en general", "¿Cuál es el nombre popular que usan los jóvenes en Puerto Rico para referirse a las competencias de la LAI?", { A: "Olimpiadas Boricuas", B: "Festival Deportivo Estudiantil", C: "Las Justas", D: "Juegos de Verano" }, "C"),
  buildQuestion(1, 12, "Justas LAI en general", "¿Qué tipo de eventos nocturnos complementan las competencias deportivas durante la semana de Justas?", { A: "Proyecciones de películas", B: "Torneos de ajedrez", C: "Conciertos y tarimas musicales", D: "Competiciones de gastronomía" }, "C"),
  buildQuestion(1, 13, "Justas LAI en general", "¿En qué año se permitió oficialmente la participación femenina en los deportes de la LAI?", { A: "1950", B: "1969-70", C: "1985", D: "2000" }, "B"),
  buildQuestion(1, 14, "Justas LAI en general", "¿Qué deporte fue el primero en tener un equipo mixto en la historia de la LAI?", { A: "Fútbol", B: "Natación", C: "Porrismo (cheerleading)", D: "Baloncesto" }, "C"),
  buildQuestion(1, 15, "Justas LAI en general", "¿Cuántas disciplinas deportivas actualmente ofrece la LAI para mujeres?", { A: "10", B: "12", C: "18", D: "20" }, "C"),
  buildQuestion(1, 16, "Justas LAI en general", "¿Cuál es el efecto de las Justas sobre los hoteles de la ciudad sede?", { A: "Ocupación parcial", B: "Se mantienen vacíos", C: "Ocupación total, sold out", D: "Solo algunos se llenan" }, "C"),
  buildQuestion(1, 17, "Justas LAI en general", "¿Quién fue uno de los fundadores principales de la Liga Atlética Interuniversitaria en 1929?", { A: "Rebekah Colberg", B: "Cosme Beitía Sálamo", C: "José Juan Barea", D: "Javier Culson" }, "B"),
  buildQuestion(1, 18, "Justas LAI en general", "¿Cuántas personas se estima que asisten a las competencias de atletismo durante las Justas?", { A: "5,000", B: "10,000", C: "20,000", D: "50,000" }, "C"),
  buildQuestion(1, 19, "Justas LAI en general", "¿Qué evento provocó la suspensión de las Justas LAI en 2020 y 2021?", { A: "Huracán María", B: "Protestas estudiantiles", C: "Pandemia de COVID-19", D: "Juegos Centroamericanos" }, "C"),
  buildQuestion(1, 20, "Justas LAI en general", "¿Qué lema refleja la misión educativa y deportiva de la LAI?", { A: "Más que deportes, una pasión", B: "Construyendo futuros brillantes", C: "Universidades en competencia", D: "Por Puerto Rico y el deporte" }, "B"),

  buildQuestion(2, 1, "Historia de las Justas en Mayagüez", "¿En qué año se celebraron por primera vez las Justas de Atletismo de la LAI en Mayagüez?", { A: "1929", B: "1930", C: "1942", D: "1969" }, "B"),
  buildQuestion(2, 2, "Historia de las Justas en Mayagüez", "¿Qué universidad ganó las primeras Justas celebradas en Mayagüez?", { A: "UPR Mayagüez", B: "UPR Río Piedras", C: "Universidad Interamericana", D: "Universidad del Sagrado Corazón" }, "A"),
  buildQuestion(2, 3, "Historia de las Justas en Mayagüez", "¿Qué estadio moderno se utiliza para las Justas en Mayagüez actualmente?", { A: "Estadio Isidoro García", B: "Estadio Centroamericano José Antonio Figueroa Freyre", C: "Coliseo Rafael Mangual", D: "Palacio de Recreación y Deportes" }, "B"),
  buildQuestion(2, 4, "Historia de las Justas en Mayagüez", "¿En qué año regresaron las Justas a Mayagüez como parte de la preparación para un evento internacional?", { A: "2008", B: "2010", C: "2012", D: "2014" }, "B"),
  buildQuestion(2, 5, "Historia de las Justas en Mayagüez", "¿Qué evento se celebró en Mayagüez en 2010 aparte de las Justas?", { A: "Juegos Panamericanos", B: "Juegos Centroamericanos y del Caribe", C: "Copa Mundial de Atletismo", D: "Juegos Olímpicos Juveniles" }, "B"),
  buildQuestion(2, 6, "Historia de las Justas en Mayagüez", "¿Cuántas veces ha sido sede Mayagüez de las Justas de la LAI hasta el 2025?", { A: "3", B: "4", C: "5", D: "6" }, "C"),
  buildQuestion(2, 7, "Historia de las Justas en Mayagüez", "¿Qué inversión hizo Mayagüez para asegurar las Justas 2025?", { A: "$100,000", B: "$150,000", C: "$200,000", D: "$250,000" }, "B"),
  buildQuestion(2, 8, "Historia de las Justas en Mayagüez", "¿Qué impacto económico tienen las Justas en Mayagüez?", { A: "Mínimo", B: "Neutro", C: "Muy alto para hoteles, comercios y transporte", D: "Solo afecta a universidades" }, "C"),
  buildQuestion(2, 9, "Historia de las Justas en Mayagüez", "¿Dónde se llevan a cabo las competencias de natación en Mayagüez durante las Justas?", { A: "Estadio Centroamericano", B: "Natatorio del RUM", C: "Coliseo Isidoro García", D: "Litoral Shorty Castro" }, "B"),
  buildQuestion(2, 10, "Historia de las Justas en Mayagüez", "¿Qué evento deportivo se realiza en el Litoral Shorty Castro durante las Justas?", { A: "Atletismo", B: "Fútbol", C: "Voleibol de playa", D: "Baloncesto" }, "C"),
  buildQuestion(2, 11, "Historia de las Justas en Mayagüez", "¿Qué recinto es conocido como \"El Colegio\" y anfitrión natural de las Justas en Mayagüez?", { A: "UPR Río Piedras", B: "UPR Mayagüez", C: "Universidad Interamericana", D: "Universidad Central de Bayamón" }, "B"),
  buildQuestion(2, 12, "Historia de las Justas en Mayagüez", "¿Qué expresión típica usan los colegiales para celebrar victorias en las Justas?", { A: "¡Vamos Vaqueros!", B: "¡Ahora y siempre Colegio!", C: "¡Arriba Inter!", D: "¡Fuerza Católica!" }, "B"),
  buildQuestion(2, 13, "Historia de las Justas en Mayagüez", "¿Cuál fue el primer año en que la competencia de porrismo se celebró oficialmente en Mayagüez?", { A: "2007", B: "2010", C: "2016", D: "2024" }, "B"),
  buildQuestion(2, 14, "Historia de las Justas en Mayagüez", "¿Qué evento de cultura popular acompaña las Justas en Mayagüez?", { A: "Festival Gastronómico", B: "Festival de Música Urbana y Tarimas", C: "Concurso de Ciencia", D: "Feria de Autos" }, "B"),
  buildQuestion(2, 15, "Historia de las Justas en Mayagüez", "¿Qué nuevo evento de atletismo se añadió en Mayagüez en 2023?", { A: "Relevo 4×100 mixto", B: "Relevo 4×400 mixto", C: "Salto triple mixto", D: "Carrera de 3,000 m obstáculos" }, "B"),
  buildQuestion(2, 16, "Historia de las Justas en Mayagüez", "¿Qué universidad se ha destacado en porrismo en Mayagüez ganando en 2022 y 2024?", { A: "UPR Río Piedras", B: "UPR Bayamón", C: "UPR Mayagüez", D: "Universidad Interamericana" }, "C"),
  buildQuestion(2, 17, "Historia de las Justas en Mayagüez", "¿Cuándo se suspendieron las Justas por última vez antes de su celebración en Mayagüez?", { A: "2017", B: "2019", C: "2020", D: "2021" }, "C"),
  buildQuestion(2, 18, "Historia de las Justas en Mayagüez", "¿Qué edificio importante del Colegio alberga eventos culturales durante la semana de Justas?", { A: "Natatorio del RUM", B: "Coliseo Rafael Mangual", C: "Teatro del RUM", D: "Biblioteca General" }, "C"),
  buildQuestion(2, 19, "Historia de las Justas en Mayagüez", "¿Qué instalación deportiva se utiliza para partidos de béisbol asociados a actividades durante las Justas?", { A: "Palacio de Recreación y Deportes", B: "Estadio Isidoro García", C: "Estadio Centroamericano", D: "Cancha Félix \"Tito\" Trinidad" }, "B"),
  buildQuestion(2, 20, "Historia de las Justas en Mayagüez", "¿Qué universidad ganó la Copa Luis F. Sambolín en 2023 mientras las Justas se celebraban en Mayagüez?", { A: "UPR Río Piedras", B: "Universidad Interamericana", C: "UAGM (Ana G. Méndez)", D: "UPR Mayagüez" }, "C"),

  buildQuestion(3, 1, "Justas LAI Baloncesto 2024-2025", "¿Quiénes ganaron el campeonato de baloncesto masculino de las Justas LAI en 2024?", { A: "Vaqueros de UPR Bayamón", B: "Taínos de UAGM", C: "Tarzanes de UPR Mayagüez", D: "Halcones de UCB" }, "C"),
  buildQuestion(3, 2, "Justas LAI Baloncesto 2024-2025", "¿Cuántos años pasaron desde que UPR Mayagüez había ganado su último campeonato de baloncesto antes del 2024?", { A: "10 años", B: "20 años", C: "31 años", D: "5 años" }, "C"),
  buildQuestion(3, 3, "Justas LAI Baloncesto 2024-2025", "¿Quién fue el Jugador Más Valioso de la final masculina 2024?", { A: "Emanuel Andújar", B: "Jeriel Zayas", C: "César Barrio", D: "Roberto Nieves" }, "B"),
  buildQuestion(3, 4, "Justas LAI Baloncesto 2024-2025", "¿Contra qué universidad jugaron los Tarzanes de UPR Mayagüez la final masculina 2024?", { A: "UPR Bayamón", B: "UAGM", C: "UPR Río Piedras", D: "UPR Ponce" }, "B"),
  buildQuestion(3, 5, "Justas LAI Baloncesto 2024-2025", "¿Qué universidad ganó el campeonato de baloncesto femenino en 2024?", { A: "UPR Bayamón", B: "UAGM", C: "UPR Mayagüez", D: "PUCPR" }, "C"),
  buildQuestion(3, 6, "Justas LAI Baloncesto 2024-2025", "¿Cómo terminó el marcador de la final femenina 2024?", { A: "70-65", B: "55-54", C: "62-61", D: "66-64" }, "C"),
  buildQuestion(3, 7, "Justas LAI Baloncesto 2024-2025", "¿Qué equipo masculino llegó a su primera final de baloncesto en 2025?", { A: "Tarzanes de UPRM", B: "Vaqueros de UPR Bayamón", C: "Halcones de la UCB", D: "Taínos de UAGM" }, "C"),
  buildQuestion(3, 8, "Justas LAI Baloncesto 2024-2025", "¿Quiénes fueron los finalistas masculinos en 2025?", { A: "UPR Río Piedras vs UPR Bayamón", B: "UPR Mayagüez vs UCB", C: "UAGM vs PUCPR", D: "UPR Ponce vs Interamericana" }, "B"),
  buildQuestion(3, 9, "Justas LAI Baloncesto 2024-2025", "¿Qué universidad fue subcampeona masculina en 2024?", { A: "UPR Bayamón", B: "UAGM", C: "UPR Ponce", D: "Interamericana" }, "B"),
  buildQuestion(3, 10, "Justas LAI Baloncesto 2024-2025", "¿Cuál fue la protesta presentada en la final masculina de 2024?", { A: "Fallo de árbitros", B: "Mal conteo de puntos", C: "Protesta de elegibilidad de jugadores de UAGM", D: "Falla en la instalación de la cancha" }, "C"),
  buildQuestion(3, 11, "Justas LAI Baloncesto 2024-2025", "¿Quién fue la MVP femenina del torneo 2024?", { A: "Nashaly Potts", B: "Vivian Hernández", C: "Victoria Suárez", D: "Estefanía Soto" }, "C"),
  buildQuestion(3, 12, "Justas LAI Baloncesto 2024-2025", "¿Cuál fue el marcador de la semifinal donde UCB eliminó a UAGM en 2025?", { A: "75-73", B: "82-74", C: "65-62", D: "80-77" }, "B"),
  buildQuestion(3, 13, "Justas LAI Baloncesto 2024-2025", "¿Quién fue uno de los jugadores destacados de UCB en su camino a la final 2025?", { A: "Jeriel Zayas", B: "Francisco Osorio", C: "Emanuel Andújar", D: "César Barrio" }, "B"),
  buildQuestion(3, 14, "Justas LAI Baloncesto 2024-2025", "¿Qué universidad clasificó al juego por el tercer lugar en masculino en 2025?", { A: "UPR Ponce", B: "UPR Bayamón", C: "PUCPR", D: "Interamericana" }, "A"),
  buildQuestion(3, 15, "Justas LAI Baloncesto 2024-2025", "¿Quiénes jugaron la final femenina 2025?", { A: "UPR Río Piedras vs UPR Mayagüez", B: "UPR Bayamón vs UPR Mayagüez", C: "UAGM vs UPR Mayagüez", D: "PUCPR vs UPR Bayamón" }, "B"),
  buildQuestion(3, 16, "Justas LAI Baloncesto 2024-2025", "¿Cuántos campeonatos consecutivos buscaron las Juanas de UPR Mayagüez en 2025?", { A: "2", B: "3", C: "4", D: "5" }, "B"),
  buildQuestion(3, 17, "Justas LAI Baloncesto 2024-2025", "¿Qué equipo femenino llegó invicto a la final 2025?", { A: "UPR Río Piedras", B: "UPR Bayamón", C: "PUCPR", D: "UAGM" }, "B"),
  buildQuestion(3, 18, "Justas LAI Baloncesto 2024-2025", "¿En qué recinto se jugaron las finales de baloncesto en 2024 y 2025?", { A: "Coliseo Roberto Clemente", B: "Coliseo Mario Morales", C: "Palacio de Recreación y Deportes de Mayagüez", D: "Auditorio Juan Pachín Vicéns" }, "C"),
  buildQuestion(3, 19, "Justas LAI Baloncesto 2024-2025", "¿Qué aplicación se utilizó para seguir los resultados de baloncesto en 2024-2025?", { A: "FIBA LiveStats", B: "Easy Tournament (Copa Fácil)", C: "NCAA App", D: "HoopStats PR" }, "B"),
  buildQuestion(3, 20, "Justas LAI Baloncesto 2024-2025", "¿Qué frase representa el orgullo del RUM tras ganar en baloncesto?", { A: "¡Bayamón arriba!", B: "¡Ahora y siempre Colegio!", C: "¡Vamos Vaqueros!", D: "¡Fuerza Tarzán!" }, "B"),

  buildQuestion(4, 1, "Justas LAI Baile 2024-2025", "¿En qué año el baile se convirtió en deporte oficial de la LAI?", { A: "2022", B: "2023", C: "2024", D: "2025" }, "C"),
  buildQuestion(4, 2, "Justas LAI Baile 2024-2025", "¿Qué universidad ganó el primer campeonato oficial de Baile LAI en 2024?", { A: "PUCPR", B: "UPR Río Piedras", C: "UPR Mayagüez", D: "UAGM" }, "B"),
  buildQuestion(4, 3, "Justas LAI Baile 2024-2025", "¿Cuántas veces consecutivas ha ganado el equipo de baile de UPR Río Piedras contando exhibiciones y oficial?", { A: "2", B: "3", C: "4", D: "5" }, "B"),
  buildQuestion(4, 4, "Justas LAI Baile 2024-2025", "¿Cuál fue la puntuación del equipo campeón de Baile en 2024?", { A: "350.25", B: "399.15", C: "375.70", D: "405.20" }, "B"),
  buildQuestion(4, 5, "Justas LAI Baile 2024-2025", "¿A qué universidad representaba el equipo que quedó subcampeón en Baile 2024?", { A: "UPR Mayagüez", B: "PUCPR (Pontificia Universidad Católica de PR)", C: "UPR Bayamón", D: "Interamericana" }, "B"),
  buildQuestion(4, 6, "Justas LAI Baile 2024-2025", "¿Qué universidad logró el tercer lugar en baile 2024?", { A: "UPR Ponce", B: "UPR Humacao", C: "UAGM", D: "UPR Arecibo" }, "A"),
  buildQuestion(4, 7, "Justas LAI Baile 2024-2025", "¿Cuántas universidades participaron en la competencia oficial de Baile en 2024?", { A: "8", B: "10", C: "11", D: "14" }, "C"),
  buildQuestion(4, 8, "Justas LAI Baile 2024-2025", "¿Cuáles son algunos de los estilos de baile que presentaron los equipos?", { A: "Ballet y salsa", B: "Hip-Hop, Jazz Funk, Contemporáneo", C: "Tango y vals", D: "Flamenco y salsa clásica" }, "B"),
  buildQuestion(4, 9, "Justas LAI Baile 2024-2025", "¿Cuál es uno de los criterios principales que se evalúan en las competencias de baile?", { A: "Tiempo de presentación", B: "Número de bailarines", C: "Grado de dificultad de la coreografía", D: "Número de canciones" }, "C"),
  buildQuestion(4, 10, "Justas LAI Baile 2024-2025", "¿Quién lidera el equipo de baile campeón de UPR Río Piedras?", { A: "Terrency Marie’s Romero", B: "Luis Enrique Rodríguez", C: "Victoria Suárez", D: "Jan Paul Rodríguez" }, "A"),
  buildQuestion(4, 11, "Justas LAI Baile 2024-2025", "¿A cuánto fue la diferencia de puntos entre el primer y segundo lugar en Baile 2024?", { A: "1.5 puntos", B: "2.0 puntos", C: "0.45 puntos", D: "3.5 puntos" }, "C"),
  buildQuestion(4, 12, "Justas LAI Baile 2024-2025", "¿Qué universidad fue una de las revelaciones en la competencia de Baile 2024?", { A: "UPR Arecibo", B: "PUCPR", C: "UPR Humacao", D: "UPR Mayagüez" }, "B"),
  buildQuestion(4, 13, "Justas LAI Baile 2024-2025", "¿Qué duración aproximada tienen las rutinas de baile en competencia?", { A: "1 minuto", B: "2-3 minutos", C: "4-5 minutos", D: "Más de 6 minutos" }, "B"),
  buildQuestion(4, 14, "Justas LAI Baile 2024-2025", "¿Qué tipo de elementos creativos suelen incluir los equipos en sus coreografías?", { A: "Drones", B: "Utilería como sombreros o bastones", C: "Pirotecnia", D: "Carros alegóricos" }, "B"),
  buildQuestion(4, 15, "Justas LAI Baile 2024-2025", "¿Qué evento se programó para la final de baile en 2025?", { A: "Coliseo Roberto Clemente", B: "Auditorio Juan Pachín Vicéns", C: "Palacio de Recreación y Deportes de Mayagüez", D: "Estadio Centroamericano" }, "C"),
  buildQuestion(4, 16, "Justas LAI Baile 2024-2025", "¿Qué universidad buscaba su cuarto campeonato consecutivo contando exhibiciones en baile en 2025?", { A: "UPR Mayagüez", B: "PUCPR", C: "UPR Río Piedras", D: "UAGM" }, "C"),
  buildQuestion(4, 17, "Justas LAI Baile 2024-2025", "¿Cuál es uno de los objetivos de las competencias de baile LAI?", { A: "Reclutar atletas de pista y campo", B: "Fomentar el intercambio cultural y artístico", C: "Recaudar fondos para la LAI", D: "Disminuir la matrícula estudiantil" }, "B"),
  buildQuestion(4, 18, "Justas LAI Baile 2024-2025", "¿Qué plataforma transmitió en vivo la competencia de Baile 2024?", { A: "Univisión Puerto Rico", B: "ABC Puerto Rico", C: "WAPA Deportes", D: "Telemundo" }, "C"),
  buildQuestion(4, 19, "Justas LAI Baile 2024-2025", "¿Qué tipo de música predomina en las rutinas de baile universitario?", { A: "Merengue clásico", B: "Hip-Hop y fusiones urbanas", C: "Ópera", D: "Jazz clásico" }, "B"),
  buildQuestion(4, 20, "Justas LAI Baile 2024-2025", "¿Qué beneficio tienen las universidades al ganar en Baile LAI?", { A: "Premios en dinero", B: "No reciben ningún beneficio", C: "Suman puntos para la Copa Luis F. Sambolín", D: "Solo reciben trofeos" }, "C"),

  buildQuestion(5, 1, "Justas LAI Porrismo 2024-2025", "¿Quién ganó el campeonato de porrismo de las Justas LAI en 2024?", { A: "UPR Bayamón", B: "UPR Río Piedras", C: "UPR Mayagüez", D: "Universidad Interamericana" }, "C"),
  buildQuestion(5, 2, "Justas LAI Porrismo 2024-2025", "¿Qué puntuación logró el equipo campeón de porrismo de UPR Mayagüez en 2024?", { A: "142.70", B: "155.80", C: "152.00", D: "160.90" }, "B"),
  buildQuestion(5, 3, "Justas LAI Porrismo 2024-2025", "¿Quién obtuvo el subcampeonato de porrismo en 2024?", { A: "UPR Río Piedras", B: "PUCPR", C: "UPR Bayamón", D: "UAGM" }, "C"),
  buildQuestion(5, 4, "Justas LAI Porrismo 2024-2025", "¿Quién obtuvo la medalla de bronce en porrismo 2024?", { A: "PUCPR", B: "UPR Río Piedras", C: "Interamericana", D: "UAGM" }, "B"),
  buildQuestion(5, 5, "Justas LAI Porrismo 2024-2025", "¿Cuántas universidades compitieron oficialmente en porrismo en 2024?", { A: "3", B: "5", C: "7", D: "10" }, "B"),
  buildQuestion(5, 6, "Justas LAI Porrismo 2024-2025", "¿Desde qué año es el porrismo un deporte oficial en la LAI?", { A: "2003", B: "2007", C: "2012", D: "2016" }, "B"),
  buildQuestion(5, 7, "Justas LAI Porrismo 2024-2025", "¿El porrismo universitario LAI es practicado por?", { A: "Solo mujeres", B: "Solo hombres", C: "Equipos mixtos de hombres y mujeres", D: "Equipos divididos por género" }, "C"),
  buildQuestion(5, 8, "Justas LAI Porrismo 2024-2025", "¿Cuánto dura aproximadamente una rutina de porrismo en la LAI?", { A: "1 minuto", B: "2-3 minutos", C: "4-5 minutos", D: "6-8 minutos" }, "B"),
  buildQuestion(5, 9, "Justas LAI Porrismo 2024-2025", "¿Qué elementos se combinan en una rutina de porrismo LAI?", { A: "Solo baile", B: "Baile, acrobacias y formación de pirámides", C: "Solo porras habladas", D: "Solo competencias de gimnasia" }, "B"),
  buildQuestion(5, 10, "Justas LAI Porrismo 2024-2025", "¿Qué se penaliza en una rutina de porrismo?", { A: "Gritos de ánimo", B: "Faltas de sincronización o caídas en acrobacias", C: "Uso de música moderna", D: "Movimientos de hip hop" }, "B"),
  buildQuestion(5, 11, "Justas LAI Porrismo 2024-2025", "¿Qué universidad fue campeona inicial de porrismo LAI en 2007-08?", { A: "UPR Río Piedras", B: "UPR Bayamón", C: "UPR Mayagüez", D: "Interamericana" }, "B"),
  buildQuestion(5, 12, "Justas LAI Porrismo 2024-2025", "¿Qué tipo de maniobras impresionaron más en 2024?", { A: "Coreografías lentas", B: "Pirámides humanas a tres niveles y mortales en lanzamientos", C: "Solo bailes tradicionales", D: "Saltos sin acrobacias" }, "B"),
  buildQuestion(5, 13, "Justas LAI Porrismo 2024-2025", "¿Dónde se realizó la competencia de porrismo en 2024 y 2025?", { A: "Coliseo Mario Morales", B: "Auditorio Juan Pachín Vicéns", C: "Palacio de Recreación y Deportes de Mayagüez", D: "Estadio Hiram Bithorn" }, "C"),
  buildQuestion(5, 14, "Justas LAI Porrismo 2024-2025", "¿A qué nivel de dificultad internacional se aproximan algunas maniobras de porrismo LAI?", { A: "Nivel 2", B: "Nivel 3", C: "Nivel 4-5", D: "Nivel 1" }, "C"),
  buildQuestion(5, 15, "Justas LAI Porrismo 2024-2025", "¿Qué universidades protagonizan la mayor rivalidad en porrismo actualmente?", { A: "UPR Río Piedras vs Interamericana", B: "UPR Bayamón vs UPR Mayagüez", C: "PUCPR vs UAGM", D: "UPR Humacao vs UPR Arecibo" }, "B"),
  buildQuestion(5, 16, "Justas LAI Porrismo 2024-2025", "¿Cuál es una ventaja de competir en porrismo para las universidades?", { A: "Solo ganan trofeos", B: "No tiene ningún beneficio", C: "Acumulan puntos para la Copa Luis F. Sambolín", D: "Pueden graduarse más rápido" }, "C"),
  buildQuestion(5, 17, "Justas LAI Porrismo 2024-2025", "¿Qué seguridad se exige en la competencia de porrismo LAI?", { A: "Solo uso de cascos", B: "Presencia de médicos, colchonetas y observadores de seguridad", C: "Competir sin protección", D: "Solo una evaluación visual" }, "B"),
  buildQuestion(5, 18, "Justas LAI Porrismo 2024-2025", "¿Quiénes evalúan las competencias de porrismo LAI?", { A: "Estudiantes voluntarios", B: "Profesores universitarios", C: "Jueces especializados en gimnasia y cheerleading", D: "Solo fanáticos" }, "C"),
  buildQuestion(5, 19, "Justas LAI Porrismo 2024-2025", "¿Cuál es una tendencia reciente en porrismo LAI?", { A: "Coreografías de salsa", B: "Uso de música clásica", C: "Incorporar elementos de plena puertorriqueña en las rutinas", D: "Correr maratones" }, "C"),
  buildQuestion(5, 20, "Justas LAI Porrismo 2024-2025", "¿Qué expresa mejor el espíritu de los equipos de porrismo en la LAI?", { A: "Solamente ganar medallas", B: "Compartir pasión, trabajo en equipo y orgullo universitario", C: "Aumentar matrícula de la universidad", D: "Hacer campañas publicitarias" }, "B"),
];
