import type { Question } from "@/lib/types/game";

export const SAMPLE_QUESTIONS: Question[] = [
  {
    questionId: "sample-1",
    sourceRowId: "sample-1",
    prompt: "Which planet is known as the Red Planet?",
    choices: { A: "Mars", B: "Venus", C: "Mercury", D: "Jupiter" },
    correctChoice: "A",
    category: "Science",
    difficulty: "easy",
    isActive: true,
  },
  {
    questionId: "sample-2",
    sourceRowId: "sample-2",
    prompt: "Who wrote the play Romeo and Juliet?",
    choices: { A: "Jane Austen", B: "William Shakespeare", C: "Charles Dickens", D: "Mark Twain" },
    correctChoice: "B",
    category: "Literature",
    difficulty: "easy",
    isActive: true,
  },
  {
    questionId: "sample-3",
    sourceRowId: "sample-3",
    prompt: "What is the capital city of Japan?",
    choices: { A: "Kyoto", B: "Osaka", C: "Tokyo", D: "Nagoya" },
    correctChoice: "C",
    category: "Geography",
    difficulty: "easy",
    isActive: true,
  },
  {
    questionId: "sample-4",
    sourceRowId: "sample-4",
    prompt: "Which gas do plants absorb from the atmosphere?",
    choices: { A: "Oxygen", B: "Carbon Dioxide", C: "Nitrogen", D: "Helium" },
    correctChoice: "B",
    category: "Science",
    difficulty: "easy",
    isActive: true,
  },
  {
    questionId: "sample-5",
    sourceRowId: "sample-5",
    prompt: "In computing, what does CPU stand for?",
    choices: {
      A: "Central Processing Unit",
      B: "Computer Program Utility",
      C: "Central Peripheral Unit",
      D: "Core Processing Utility",
    },
    correctChoice: "A",
    category: "Technology",
    difficulty: "easy",
    isActive: true,
  },
  {
    questionId: "sample-6",
    sourceRowId: "sample-6",
    prompt: "Which ocean is the largest on Earth?",
    choices: { A: "Atlantic", B: "Arctic", C: "Pacific", D: "Indian" },
    correctChoice: "C",
    category: "Geography",
    difficulty: "easy",
    isActive: true,
  },
  {
    questionId: "sample-7",
    sourceRowId: "sample-7",
    prompt: "How many players are on a standard soccer team on the field?",
    choices: { A: "9", B: "10", C: "11", D: "12" },
    correctChoice: "C",
    category: "Sports",
    difficulty: "easy",
    isActive: true,
  },
  {
    questionId: "sample-8",
    sourceRowId: "sample-8",
    prompt: "What is H2O more commonly known as?",
    choices: { A: "Salt", B: "Water", C: "Hydrogen", D: "Oxygen" },
    correctChoice: "B",
    category: "Science",
    difficulty: "easy",
    isActive: true,
  },
  {
    questionId: "sample-9",
    sourceRowId: "sample-9",
    prompt: "Which artist painted the Mona Lisa?",
    choices: { A: "Vincent van Gogh", B: "Pablo Picasso", C: "Claude Monet", D: "Leonardo da Vinci" },
    correctChoice: "D",
    category: "Art",
    difficulty: "easy",
    isActive: true,
  },
  {
    questionId: "sample-10",
    sourceRowId: "sample-10",
    prompt: "Which country hosted the 2016 Summer Olympics?",
    choices: { A: "China", B: "Brazil", C: "United Kingdom", D: "Japan" },
    correctChoice: "B",
    category: "Sports",
    difficulty: "easy",
    isActive: true,
  },
];
